package top.oxff.model;

public enum SelectionPositionType {
    HEADER_FIRST_LINE,
    SUB_HEADER_FIRST_LINE,
    IN_HEADER_FIRST_LINE,
    SUB_HEADER_LINES,
    HEADER_OTHER_LINES,
    ALL_HEADER_LINES,
    ALL_HEADER_LINES_AND_BLANK_LINES_BEFORE_BODY,
    ALL_HEADER_LINES_AND_BLANK_LINES_AND_SUB_BODY,
    BETWEEN_HEADER_END_AND_BODY,
    SUB_BODY,
    IN_BODY,
    BODY,
    NONE,
    ALL;
}
